import type { Metadata } from "next";
import { Geist, Geist_Mono, Charm } from "next/font/google";
import Local from "next/font/local";
import "./globals.css";
 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lineSeed = Local({
  src: "../../public/fonts/LINESeedSansTH_W_Bd.woff2",
  variable: "--font-line-seed",
})

const someThaiFont = Charm({
  weight: "400",
  subsets: ["thai"],
  variable: "--font-srisakdi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${lineSeed.variable} ${geistMono.variable} ${lineSeed.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
